# Site settings
title: "Ashita's Writings"
description: "Collections of poems & prose written by Ashita"
baseurl: ""
url: "http://www.poemandprose.com"

# Build settings
markdown: kramdown
permalink: pretty
